### ISSUE TITLE
keography not appearing in flathub.org

### ISSUE THREAD

**Issue by jgarciao** [flathub/org.kde.kgeography#5]
Flathub.org (the website) gets the information about the apps from the appstream.xml file generated in the ostree repo. You can see the contents in your computer opening this file: /var/lib/flatpak/appstream/flathub/x86_64/active/appstream.xml

This app is not appearing in the website because it has some issues in the appstream information:

```
*  <component type="generic"> `should be `<component type="desktop">
```

**Comment by aleixpol** [comment]
Will be fixed in the next stable release:
https://commits.kde.org/kgeography/6a1827ee738894e1742e1e5554ada638f497e73d

**Comment by cho2** [comment]
![screenshot-flathub org-2021 09 03-08_32_13](https://user-images.githubusercontent.com/6271071/131937154-4dc4d804-6fbf-425d-80f7-197b49db7931.png)
